#!/bin/sh
#
# description: remove thelinkbox startup scripts from FreeBSD
# $Id: uninstall,v 1.1.1.1 2007/04/07 23:55:39 wb6ymh Exp $

set -x
rm /usr/local/etc/rc.d/tlb.sh
cd ..
make uninstall
cd FreeBSD

